apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  DB_URL_BANK: jdbc:mysql://10.16.16.3:3306/banking?createDatabaseIfNotExist=true
  DB_URL_PAYM: jdbc:mysql://10.16.16.5:3306/payments?createDatabaseIfNotExist=true
  HOSTNAME_RABBITMQ: rabbitmq-service.default.svc.cluster.local
