apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-banking-service
  labels:
    app: banking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
    spec:
      containers:
        - name: banking-service
          image: andreim98/banking-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL_BANK
              valueFrom:
                configMapKeyRef:
                  key: DB_URL_BANK
                  name: configmap
            - name: DB_USER_BANK
              valueFrom:
                secretKeyRef:
                  key: DB_USER_BANK
                  name: secret-banking-api
            - name: DB_PASS_BANK
              valueFrom:
                secretKeyRef:
                  key: DB_PASS_BANK
                  name: secret-banking-api
            - name: HOSTNAME_RABBITMQ
              valueFrom:
                configMapKeyRef:
                  key: HOSTNAME_RABBITMQ
                  name: configmap
            - name: USER_RABBITMQ
              valueFrom:
                secretKeyRef:
                  key: USER_RABBITMQ
                  name: secret-rabbitmq
            - name: PASS_RABBITMQ
              valueFrom:
                secretKeyRef:
                  key: PASS_RABBITMQ
                  name: secret-rabbitmq
            - name: URL_PAYMENT_SVC
              valueFrom:
                configMapKeyRef:
                  key: URL_PAYMENT_SVC
                  name: configmap
          resources:
            requests:
              memory: "1500Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 30001
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 30001
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: banking-service
spec:
  selector:
    app: banking-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
