apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-payment-service
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-service
          image: andreim98/payment-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL_PAYM
              valueFrom:
                configMapKeyRef:
                  key: DB_URL_PAYM
                  name: configmap
            - name: DB_USER_PAYM
              valueFrom:
                secretKeyRef:
                  key: DB_USER_PAYM
                  name: secret-payment-api
            - name: DB_PASS_PAYM
              valueFrom:
                secretKeyRef:
                  key: DB_PASS_PAYM
                  name: secret-payment-api
            - name: HOSTNAME_RABBITMQ
              valueFrom:
                configMapKeyRef:
                  key: HOSTNAME_RABBITMQ
                  name: configmap
            - name: USER_RABBITMQ
              valueFrom:
                secretKeyRef:
                  key: USER_RABBITMQ
                  name: secret-rabbitmq
            - name: PASS_RABBITMQ
              valueFrom:
                secretKeyRef:
                  key: PASS_RABBITMQ
                  name: secret-rabbitmq
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: ClusterIP
  ports:
    - name: http
      port: 8082
