server:
  port: 8080
  servlet:
    context-path: /api

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  rabbitmq:
    hostname: ${HOSTNAME_RABBITMQ}
    username: ${USER_RABBITMQ}
    password: ${PASS_RABBITMQ}
    port: 5672
    exchange: payment.exchange
    routingkey: payment.routingkey

  datasource:
    url: ${DB_URL_BANK}
    username: ${DB_USER_BANK}
    password: ${DB_PASS_BANK}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
