server:
  port: 8082

spring:
  rabbitmq:
    hostname: localhost
    username: guest
    password: guest
    port: 5672
    exchange: payment.exchange
    routingkey: payment.routingkey
    queue: payment.queue

  datasource:
    url: jdbc:mysql://localhost:3306/consults?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa.show-sql: true
